name: Пинг для Render

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Пинг сайта
        run: curl -s https://walletback-aghp.onrender.com