name: Пинг для Render

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Пинг backend
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://walletback-aghp.onrender.com/ping)
          echo "Ответ: $RESPONSE"
          if [ "$RESPONSE" = "200" ]; then
            echo "Backend жив!"
          else
            echo "Ошибка: $RESPONSE"
            exit 1
          fi